# Configuracion del Config Server

server:
  port: 8081 # Puerto del Config Server

spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server # Rama en Git
          uri: https://github.com/jairoLopM06/microservices-course # Respositorio remoto en donde se va a guardar la configuracion
          search-paths: config-data # Directorio con Archivos de configuracion para cada microservicios
  application:
    name: config-service